### ISSUE TITLE
Moving hpp-template-corba from laas to humanoid-path-planer

### ISSUE THREAD

**Issue by jcarpent** [laas/hpp-template-corba#3]
hpp-template-corba is currently belonging to laas project. 
I would suggest to move it from this project to the humanoid-path-planer project.

@florent-lamiraux What do you think?

**Comment by florent-lamiraux** [comment]
Why not.
If you do so, can you keep a copy of the repository on laas project for a while, the time for us to update our links here and there ?

**Comment by jcarpent** [comment]
Ok. I will do that.
